services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: toast-frontend:latest
    ports:
      - "4000:80"
    depends_on:
      - websocket-server
      - web-server
  websocket-server:
    container_name: toast-websocket-server
    build:
      context: ./websocket-server
      dockerfile: ./Dockerfile
    image: toast-websocket-server:latest
    ports:
      - "8181:8181"
    depends_on:
      - database
      - mongodb
  web-server:
    container_name: toast-web-server
    build:
      context: ./web-server
      dockerfile: ./Dockerfile
    image: toast-web-server:latest
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
      - MONGODB_URI=mongodb://root:password@mongodb:27017
    depends_on:
      - database
      - mongodb
  database:
    image: postgres:latest
    volumes:
      - ./postgres-initdb:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
